system:
    services:
        #ENC[AES256_GCM,data:m5kb1lZXpGWE2rGnkoZJybNKh9W7qnzbEozl/JbhtYS5Q2otDkHFK+Vd1xREvOfUX1CnXgmJfUglEPFtm9scJV68HxHuqYfY7lM0lA==,iv:Y2leswlFv9qDAC7XkzYPEoXBd5k4LtD5sXgWNJCTZXQ=,tag:Vd+t3Wa3pgHs+7DX9KsEWw==,type:comment]
        traefik:
            apiTokenFile: ENC[AES256_GCM,data:gFT0EEusxbK0cBX1PZV/Id+uegqUKKBCRk72Dm2CxCj95jYRI6qipfuboKJnyvXN3AHkM8qqTYJ09KM6PEeJmaRKA0t4PaCD1PRW/K2+M16iEESNoll9Mr1wa1+0SdiBnQ==,iv:Lc08yoR7N/uES33N3ngVHr2UlZKTeCFLl9Ngnyw76Z8=,tag:lDT1ily7Jyhv0EwQ20tXAQ==,type:str]
sops:
    age:
        - recipient: age1lj5vmr02qkudvv2xedfj5tq8x93gllgpr6tzylwdlt7lud4tfv5qfqsd5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYmowRnF3eHZBaVNveXo1
            cXFEUktqZTJWL1JsY2FvRmxMVzA4MHo1a25nCmRKV0s2QWU2bDRkdGp2L0RxZG1V
            RW1DN0lscCtmYzlJTGpKM0puak92MGsKLS0tIFFuYk8vVk94K25lUEt3UDNYNlFV
            aGl4ZkJtUmVvWTVPS1JldkZFQllsTlkK5ERlD8CtwpsFOjkznMqiS3ivLg4Et5Lj
            SNLaQAvFiBGfJUenZqPyYGw4K8RKr9cXZqTsLJ5U0DgGm3Z+MZgvSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17edew3aahg3t5nte5g0a505sn96vnj8g8gqse8q06ccrrn2n3uysyshu2c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YU5Uamd0c0N2c2gySGxy
            cWFiMDQvemorTWJJOFdlZWFUc2JqTnRncWw4CkVPYzZEMmV6bjUrUEd4azRzdk0y
            cVJBRGFkNlRiYjdEc2Y0SWpDRXJVNkkKLS0tIC9vZXJaQVJGaVMvVVkrVzlUTTVx
            b0E4VjIrb21saGNHeXJkWUV2NDFRRFEK/ffiQrNOiuNs8EhIRnKKXQFxPbsF5h4q
            5jsRasKVnzIGeBPepPA4U8P5xkj1wTxK/TCpydiSbyxVWXCVn+wdjg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rpkr0le4ff550wgyazssfe8r335gjwpyflqezz7trtrhw6ygge3qgydv3y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZ1lUU056VnNERThOdHBn
            dUptQVJ2TTV0ZXJZazE0QWxyUmU0WWxvZkFnClh4TjlBY1NsVWlnUkxKSGtjTjhT
            QmJ0ZU1jMWpScTN2cUxRYUtmaFR3THcKLS0tIEVDZER6VGt4TVhtMVlXclAvdEVi
            VzVYWjhLRVpaV3VTQzV5THFaZ3kzeE0KFt6Cx9IRw3WK/vXYoMi5wgICUCZAxMYD
            MCMXLj/wIrxZa2SgQPd8e/loSgXL5w8oeHP9Il1oxV7Ya0s2n9v+mA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cp6vegrmqfkuj8nmt2u3z0sur7n0f7e9x9zmdv4zygp8j2pnucpsdkgagc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZHBGcTB2SmNOdGNySHNI
            ZVRYbUdjSUZNakdZMDlSc1hBZHBRMHhGMmpZCmM0cW8zR3dwVUJkTnk0Um5Idmdp
            KzBIeDhkdTdINTZLNkQ2Wi9NNEVIL2sKLS0tIC82RklyWVpzNit0cHZ4SWtZRU5P
            c3VUbUVJb296Q0JDT1dpVWkzK2IzQmcKybZurDMxShY0CzNoIzFi9cWvPtBGO/z9
            MGfOYIX+SpL/s/e7FNRvR5RHLSmDq95E5Ih+H9oeiOmPatqyo6+Smg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ekt5xz7u2xgdzgsrffhd9x22n80cn4thxd8zxjy2ey5vq3ca7gnqz25g5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVE9oM1lrRVVOZlZpVG16
            UnZNREMwMDRzSWgzMHNsQm94bXpCRUEvcFFrCjlRdjg2K3ZHVzJKYmMvd1ZCaDZ5
            UkpzWm5JV2R0Q2dscGdiNk9SZjJNL1UKLS0tIGwrSHRaZFZGQjZYSm9VU05BM2pR
            dnhtMUcydTRnY056cEZGUllaTVdRNVUK8cZHQRE4prDqFJrXJEJyZC2PB1gxnekC
            wSqcFFhf3Nxn+vlkkKHBMjr8CVszigcG7HZ+qUYFW13bojTq88GPLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mmdjc4qk20accal4p4yhm5d2nsnlfnmmn484pg4mqtsu70fqvy4s6namra
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZN0RvYzZmYzJHR053Mkc3
            enFwdmxTM2RsUVJBazRQaCt0OUV6OGlrWkE4Cmc2RzJjRHpBanp1aHBETU5TVVhT
            M3ExSnV4ejFIVCtkbVVteTBpVXJYaVkKLS0tIDAxYzUvemtreCtHYTdLeWdYZWU1
            a3JvS1dZeW4yZHVlU3ZvSDN3Q040RncKPuaOWQFtgA84KqM1r3i9CB3Gg7GC4Gy4
            zzHtwdniU9SSRGY397kxAXG2KnVnPWCicL3IzwFxXn/6DNl+Q29wLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j2r8mypw44uvqhfs53424h6fu2rkr5m7asl7rl3zn3xzva9m3dcqpa97gw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHY2hFZTFuQW1oY2tHOTAy
            R0luMlhVRVdzU2hVSGc1UWkyZytEZXFaV3lvCnFGUElvWHZFR0h4RytURXZBSWlV
            NnN5VU9QZjZjSHV1ZFpHQitLc3JqN2cKLS0tIFpKNHBMVjE3WUFPV0tkNXV2R3Ur
            VmRuVzhGRkQrd0VrUWxVNWdJMldLOU0K1ZR1CCsUw+NolkscDWLlde5WYQzru5X9
            TLVuR0mXO7utaPhCwwt4oAgkn76bDhKikxwaxgeLaq4MyquFW5J8QQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ezmtw7qaw93yggtcncqpyej9qjlref8au5uceqat49htmlfgps2swsttyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUTA1ZWorckFzQTZnUExt
            cEVkMEswYVB0cjdHTFdXV2RJZHNBWGNGMkNZClZ2dDR1Tk1iN2RSeDhRRnNZVVIr
            K3hCVThrSTliSjl3Sm9CdThKUG5yS3cKLS0tIElpYjNGOE4vWUxGK0p4T3RXK0Jw
            dUVPYS9NdUQzZFJjclZRNEE3RWtoZGcKVbLU1v36pkTHqbiBQxhhbNyfe4CBNCnn
            Zh82OGt5kWcvBJdezeR/ZagqH/7+iYNcZm/HN25FpZ0pUUsY3dIJCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m24gvg0wq5ps872ezcjwdx7e9rrs65rq2vt05qwt9purptxyyessasckk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZFQxU3dXRmRlenlQaisr
            eFJEK2hWYWNKaFo5QzMvNXJYOHhjOWJhcVVVCmE2eW9tR3dIWFdxZ0JHem1JSmta
            M1hoNWxFNVF2bGhWWHFJdmtGc2xJQW8KLS0tIHgvMTBBR0hvWkxCOXVaYlQ0MUVK
            NU9YK29mRkVwWDFEbXVYN2xOZUI0aWcKm5lGQJPbbJBUnZaozUjYk9pRFDAux7Qo
            A1gFfn1wynM/dFc/5Uru5TestN6eYWViM0HJri9zEbi6MmSTSAcXfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13dmfusa7kvgmc9xqzu55ws07y6etzcxa5cx58vkthdaeyuv32ecq3c624g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cThLZXJQVnV0S2MySDdO
            T1NzT0tHQzlyMlJJVGZSNHg1ejZ2eGQ0b1RjCjA5ZVAyR0ZHa1h5RmJ6S3NJd0wv
            aStRNVk1N3ZOZGc3Z0xkSVR6S0lwSzQKLS0tIGVNdTFBSU93V2ZkanZWN251ZXJx
            YSsreEFGeHQrTlBwdE1WVFEyR3k2YlUKAnXjX5DnhLwqaoLbYYUU615Uaq1Vat3K
            Pxr/mAMYOZG3ft4RXi5mZM+b3u713HmKhYVrhKRBI4pcTtXyJL2UvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T04:48:42Z"
    mac: ENC[AES256_GCM,data:JYXAuWGHDSxlkBFootDhB1Tw/wOS88HphtlO3qEfG2E89243/y03liPL1hk+XmlwJtjCPVk69WRnxxLgv/4wS8lRKsWUr2teNFCdZGR8pxOmerA2D5NDTQdlqPpjzHzzbXPnh7oJj9E0TSubnBlxOlSWIkliDHHGhURHOriQvIU=,iv:gYOoDddwxVyg5Deo6juNuGUvLqgF0yJeAqnmOHizzRY=,tag:Vka+7mPDXCCPIdv3dj5uxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
